### ISSUE TITLE
Set up internet connection for iPhone via USB

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/mcloud-ios#5] opened 2020-01-14 13:09 UTC
Due to experience, internet connection for iPhone via USB is more stable then via wi-fi. For now we use static iP on iPhone, let's investigate what will happen in case of USB sharing. The link how to set up connection is [here](https://superuser.com/questions/1214500/how-to-connect-iphone-to-internet-by-usb-cable)

**Comment by vdelendik** [comment] 2022-12-24 17:28
in 2.4 release we reused port forwarding and allowed to use iOS devices without wi-fi:
https://github.com/zebrunner/mcloud-ios/issues/143

so let's document howto enable internet via USB in readme and make this step optional. Should it be recommended or not still TBD.

**Comment by vdelendik** [comment] 2023-03-06 23:04
closing as won't fix and dupe of #143 because feature was implemented in scope of below tickets already:
https://github.com/zebrunner/mcloud-ios/issues/143
https://github.com/zebrunner/appium/issues/148
https://github.com/zebrunner/mcloud-device/issues/118
https://github.com/zebrunner/mcloud-agent/issues/155

**Closed by vdelendik** 2023-03-06 23:04 UTC
Labels: duplicate, enhancement, wontfix
