### ISSUE TITLE
Not able to see connected iPhone in STF via mcloud

### ISSUE THREAD

**Issue by Immanuel-Codoid** [zebrunner/mcloud-ios#140] opened 2022-10-09 17:00 UTC
agents.log
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: ./zebrunner.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: ./zebrunner.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: ./zebrunner.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: ./zebrunner.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: ./zebrunner.sh: Operation not permitted
```
mcloud-ios settings
```
MCloud SmartTestFarm Settings
Master host protocol [http]: 
Master host address [192.168.29.162]: 
Master host port [80]: 
MCloud STF URL: http://192.168.29.162:80/stf
Continue? y/n [y]:y

MCloud iOS Agent Settings
Current node host address []: 
```
devices.txt
```
# DEVICE NAME    |  UDID                                    |APPIUM|  WDA  | MJPEG | IWDP  | STF_SCREEN | PROXY_APPIUM 
iPhone_7         | 48ert45492kjdfhgj896fea31c175f7ab97cbc19 | 4841 | 20001 | 20002 | 20003 |  7701      |  7702
Phone_X1         | 7643aa9bd1638255f48ca6beac4285cae4f6454g | 4842 | 20011 | 20022 | 20023 |  7711      |  7712    
Dev iPhone       | 00008110-001228D036D1801E                | 4843 | 20012 | 20024 | 20048 |  7100      |  7101
```

What should be given in the current node host address?
Am I making any mistake here?
Help is much appreciated @shov @vdelendik @kolyakrasnik @okamara

**Comment by vdelendik** [comment] 2022-12-15 21:30
closing as not a bug. the reason of this failure you are trying to start shell script from deleted current dir (logs?) or read permission is not available.
Make sure to not use sudo and root permissions during cloning and setup!

**Closed by vdelendik** 2022-12-15 21:30 UTC
Labels: invalid
