### ISSUE TITLE
Gray screen on STF when opening iOS devices and simulator after more than 24 hours on standby

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#185] opened 2023-01-16 09:43 UTC
**Steps:**

1. Open ios device on  STF

**Actual result:**  Service is curretly unavailable.Try your attempt later.

<img width="975" alt="Screenshot 2023-01-16 at 12 40 44" src="https://user-images.githubusercontent.com/50950954/212646728-94fe20f4-220b-4615-a22b-45de280e7923.png">

**Logs iphone 8:**
```
idmclouds-Mac-mini:mcloud-ios idmcloud$ tail -n 100 -f ./logs/iPhone_8.log
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-15T20:01:40+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-15T20:01:40+03:00"}
{"fields.msg":"2023-01-15 20:32:28.525831+0300 WebDriverAgentRunner-Runner[13085:911959] [ProfileConnection] Public XPC connection invalidated\n","fields.time":6138413150068,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:32:28+03:00"}
{"fields.msg":"2023-01-15 20:33:26.716198+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6139809678441,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:33:26+03:00"}
{"fields.msg":"2023-01-15 20:38:48.732917+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147538166782,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:38:48+03:00"}
{"fields.msg":"2023-01-15 20:38:51.101544+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147596359623,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:38:51+03:00"}
{"fields.msg":"2023-01-15 20:38:52.735008+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147634138336,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:38:52+03:00"}
{"fields.msg":"2023-01-15 20:38:56.256054+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147725806535,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:38:56+03:00"}
{"fields.msg":"2023-01-15 20:38:58.174363+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147764711029,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:38:58+03:00"}
{"fields.msg":"2023-01-15 20:39:01.469504+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147844840830,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:01+03:00"}
{"fields.msg":"2023-01-15 20:39:05.407483+0300 WebDriverAgentRunner-Runner[13085:913713] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6147941601047,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:05+03:00"}
{"fields.msg":"2023-01-15 20:39:11.861632+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148096472876,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:12+03:00"}
{"fields.msg":"2023-01-15 20:39:21.487384+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148324228349,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:21+03:00"}
{"fields.msg":"2023-01-15 20:39:24.695864+0300 WebDriverAgentRunner-Runner[13085:914042] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148402033720,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:24+03:00"}
{"fields.msg":"2023-01-15 20:39:28.952364+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148507330714,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:29+03:00"}
{"fields.msg":"2023-01-15 20:39:31.931626+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148578050747,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:32+03:00"}
{"fields.msg":"2023-01-15 20:39:35.667981+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148667762730,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:35+03:00"}
{"fields.msg":"2023-01-15 20:39:41.710809+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148810572617,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:41+03:00"}
{"fields.msg":"2023-01-15 20:39:44.353269+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148873009434,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:44+03:00"}
{"fields.msg":"2023-01-15 20:39:45.962794+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148911649333,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:46+03:00"}
{"fields.msg":"2023-01-15 20:39:49.236986+0300 WebDriverAgentRunner-Runner[13085:915831] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6148990180781,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:49+03:00"}
{"fields.msg":"2023-01-15 20:39:50.896455+0300 WebDriverAgentRunner-Runner[13085:915831] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149030023402,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:39:50+03:00"}
{"fields.msg":"2023-01-15 20:40:23.181074+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149805068288,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:23+03:00"}
{"fields.msg":"2023-01-15 20:40:25.872870+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149869683112,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:25+03:00"}
{"fields.msg":"2023-01-15 20:40:27.136961+0300 WebDriverAgentRunner-Runner[13085:915380] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149900105626,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:27+03:00"}
{"fields.msg":"2023-01-15 20:40:29.476303+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149956144190,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:29+03:00"}
{"fields.msg":"2023-01-15 20:40:30.685343+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6149985191696,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:30+03:00"}
{"fields.msg":"2023-01-15 20:40:31.958741+0300 WebDriverAgentRunner-Runner[13085:908801] Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}\n","fields.time":6150015728732,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":13085,"time":"2023-01-15T20:40:32+03:00"}
WdaMjpeg connection was closed
2023-01-15T17:42:36.704Z INF/util:lifecycle 75456 [b09...........b7243f862b5] Winding down for graceful exit, with optional error :  WdaMjpeg connection is lost
2023-01-15T17:42:36.712Z FTL/util:lifecycle 75456 [b09f...............b7243f862b5] Shutting down due to fatal error with optional error :  WdaMjpeg connection is lost
Starting WDA: iPhone_8, udid: b09fa................3f862b5, WDA_PORT: 20001, MJPEG_PORT: 20002
[15/01/2023 20:42:39] Starting WebDriverAgent application on port 20001
Starting iSTF ios-device: b09f.............7243f862b5 device name : iPhone_8
{"bundleid":"com.facebook.WebDriverAgentRunner.xctrunner","level":"info","msg":"Running wda","testbundleid":"com.facebook.WebDriverAgentRunner.xctrunner","time":"2023-01-15T20:42:39+03:00","xctestconfig":"WebDriverAgentRunner.xctest"}
WDA started successfully on iPhone_8 within 0 seconds.
{"level":"error","msg":"process of com.facebook.WebDriverAgentRunner.xctrunner not found","time":"2023-01-15T20:42:40+03:00"}
Now using node v17.1.0 (npm v8.3.0)
/Users/idmcloud/tools/mcloud-ios/metaData/iPhone_8.env
2023-01-15T17:42:41.456Z INF/db 59291 [b09fa..........7243f862b5] Connecting to demo.zebrunner.farm:28015
2023-01-15T17:42:41.463Z INF/device:support:push 59291 [b09fa.........9e3348b7243f862b5] Ios device sending output to "tcp://demo.zebrunner.farm:7270"
2023-01-15T17:42:41.466Z INF/ios-device 59291 [b09f.............49e3348b7243f862b5] Preparing device options:  {
  serial: 'b09f.........b49e3348b7243f862b5',
  provider: 'mcloud-ios',
  publicIp: 'demo.zebrunner.farm',
  endpoints: {
    sub: [ 'tcp://demo.zebrunner.farm:7250' ],
    push: [ 'tcp://demo.zebrunner.farm:7270' ],
    appDealer: [ 'tcp://demo.zebrunner.farm:7160' ],
    devDealer: [ 'tcp://demo.zebrunner.farm:7260' ]
  },
  groupTimeout: 3600000,
  storageUrl: 'https://demo.zebrunner.farm:443/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 30,
  screenPingInterval: 30000,
  screenPort: 7701,
  screenWsUrlPattern: 'wss://demo.zebrunner.farm:443/d/192.168.89.189/b0.........b49e3348b7243f862b5/7701/',
  connectUrlPattern: '${publicIp}:${publicPort}',
  connectPort: 20002,
  wdaHost: 'localhost',
  wdaPort: 20001,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: false,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  deviceName: 'iPhone_8',
  deviceType: 'Phone',
  host: '192.168.89.189'
}
2023-01-15T17:42:41.930Z INF/device:support:sub 59291 [b09f........8b7243f862b5] Receiving input from "tcp://demo.zebrunner.farm:7250"
2023-01-15T17:42:41.932Z INF/device:support:sub 59291 [b0.........49e3348b7243f862b5] Subscribing to permanent channel "*ALL"
2023-01-15T17:42:41.936Z INF/device:plugins:solo 59291 [b09fa.......49e3348b7243f862b5] Subscribing to permanent channel "dzTlyg6o9YlxdBizOqIGbhlToWI="
2023-01-15T17:42:41.939Z INF/wdaClient 59291 [b0........e3348b7243f862b5] WdaClient.js initializing...
connecting to WdaMjpeg
2023-01-15T17:42:41.950Z INF/device:info 59291 [b09.........9e3348b7243f862b5] device.name: iPhone_8
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:20002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 20002
}

Node.js v17.1.0
^C

```

**Logs iPad 9:**

```
idmclouds-Mac-mini:mcloud-ios idmcloud$ tail -n 100 -f ./logs/iPad_9.log
Starting iSTF ios-device: 000..........0260C02E device name : iPad_9
Starting WDA: iPad_9, udid: 0000...........5C20260C02E, WDA_PORT: 20041, MJPEG_PORT: 20042
[15/01/2023 21:38:41] Starting WebDriverAgent application on port 20041
{"bundleid":"com.facebook.WebDriverAgentRunner.xctrunner","level":"info","msg":"Running wda","testbundleid":"com.facebook.WebDriverAgentRunner.xctrunner","time":"2023-01-15T21:38:41+03:00","xctestconfig":"WebDriverAgentRunner.xctest"}
Now using node v17.1.0 (npm v8.3.0)
2023-01-15T18:38:42.231Z INF/db 31962 [000..........0260C02E] Connecting to demo.zebrunner.farm:28015
2023-01-15T18:38:42.238Z INF/device:support:push 31962 [000.........20260C02E] Ios device sending output to "tcp://demo.zebrunner.farm:7270"
2023-01-15T18:38:42.241Z INF/ios-device 31962 [000..........260C02E] Preparing device options:  {
  serial: '00.........20260C02E',
  provider: 'mcloud-ios',
  publicIp: 'demo.zebrunner.farm',
  endpoints: {
    sub: [ 'tcp://demo.zebrunner.farm:7250' ],
    push: [ 'tcp://demo.zebrunner.farm:7270' ],
    appDealer: [ 'tcp://demo.zebrunner.farm:7160' ],
    devDealer: [ 'tcp://demo.zebrunner.farm:7260' ]
  },
  groupTimeout: 3600000,
  storageUrl: 'https://demo.zebrunner.farm:443/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 30,
  screenPingInterval: 30000,
  screenPort: 7711,
  screenWsUrlPattern: 'wss://demo.zebrunner.farm:443/d/192.168.89.189/00.........0260C02E/7711/',
  connectUrlPattern: '${publicIp}:${publicPort}',
  connectPort: 20042,
  wdaHost: 'localhost',
  wdaPort: 20041,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: false,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  deviceName: 'iPad_9',
  deviceType: 'Tablet',
  host: '192.168.89.189'
}
WDA started successfully on iPad_9 within 0 seconds.
2023-01-15T18:38:42.562Z INF/device:support:sub 31962 [0000........0260C02E] Receiving input from "tcp://demo.zebrunner.farm:7250"
2023-01-15T18:38:42.564Z INF/device:support:sub 31962 [00...........0260C02E] Subscribing to permanent channel "*ALL"
2023-01-15T18:38:42.567Z INF/device:plugins:solo 31962 [0000............C20260C02E] Subscribing to permanent channel "hi5vgnXKvQx0hsitADmsw1Vjxkc="
2023-01-15T18:38:42.571Z INF/wdaClient 31962 [0000..........0260C02E] WdaClient.js initializing...
connecting to WdaMjpeg
2023-01-15T18:38:42.579Z INF/device:info 31962 [00............60C02E] device.name: iPad_9
{"bundleID":"com.facebook.WebDriverAgentRunner.xctrunner","channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Launching process","time":"2023-01-15T21:38:42+03:00"}
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:20042
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 20042
}

Node.js v17.1.0
{"channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Process started successfully","pid":6619,"time":"2023-01-15T21:38:42+03:00"}
{"fields.msg":"2023-01-15 18:38:42.740755+0000 WebDriverAgentRunner-Runner[6619:958565] Running tests...\n","fields.time":6662121285649,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:42+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginExecutingTestPlan","time":"2023-01-15T21:38:43+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginInitializingForUITesting","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"Test Suite 'All tests' started at 2023-01-15 18:38:44.171\nXCTestOutputBarrier","fields.time":6662155625311,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"Test Suite 'WebDriverAgentRunner.xctest' started at 2023-01-15 18:38:44.173\nXCTestOutputBarrier","fields.time":6662155649938,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"Test Suite 'UITestingUITests' started at 2023-01-15 18:38:44.173\nXCTestOutputBarrier","fields.time":6662155656652,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"    t =      nans Suite Set Up\n","fields.time":6662155659758,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.201172+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    KeyboardAutocorrection\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156336409,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.202097+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_changedAt\"\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156357396,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.202513+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_buildAtChange\"\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156368078,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.202929+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_previousValue\"\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156377708,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.203356+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_analyzedAt\"\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156387763,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.218373+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    KeyboardPrediction\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156750278,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.218832+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    KeyboardShowPredictionBar\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156762614,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.219445+0000 WebDriverAgentRunner-Runner[6619:958565] [User Defaults] Couldn't write values for keys (\n    DidShowContinuousPathIntroduction\n) in CFPrefsPlistSource\u003c0x283ee4f00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":6662156774748,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCaseDidStartForTestClass:method:","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"Test Case '-[UITestingUITests testRunner]' started.\n","fields.time":6662156892768,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"XCTestOutputBarrier","fields.time":6662156903869,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"    t =     0.00s Start Test at 2023-01-15 18:38:44.225\n","fields.time":6662156918890,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-15T21:38:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"    t =     0.00s Set Up\n2023-01-15 18:38:44.226515+0000 WebDriverAgentRunner-Runner[6619:958565] Built at Jan 12 2023 16:18:28\n","fields.time":6662156943079,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.237558+0000 WebDriverAgentRunner-Runner[6619:958565] ServerURLHere-\u003ehttp://169.254.4.134:20041\u003c-ServerURLHere\n","fields.time":6662157209164,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
{"fields.msg":"2023-01-15 18:38:44.237822+0000 WebDriverAgentRunner-Runner[6619:958569] Using singleton test manager\n","fields.time":6662157214506,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":6619,"time":"2023-01-15T21:38:44+03:00"}
^C

```

**Comment by vdelendik** [comment] 2023-01-16 18:04
closing as dupe of #184

**Closed by vdelendik** 2023-01-16 18:04 UTC
Labels: bug, duplicate
