### ISSUE TITLE
WDA Runner couldn't write values for keys KeyboardAutocorrection after ./zebrunner.sh start-wda [udid]

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#26] opened 2021-01-04 18:21 UTC
**Test scenario:**

Steps:

1../zebrunner.sh down
2../zebrunner.sh start-wda [udid]
3.tail -n1000 -f ./logs/wda_iPhone_8_plus.log

**Actual resutl:** WDA Runner  couldn't write values for keys KeyboardAutocorrection after ./zebrunner.sh start-wda [udid]

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -derivedDataPath /opt/tools/mcloud-ios/tmp/DerivedData/d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 -scheme WebDriverAgentRunner -destination id=d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 USE_PORT=20021 MJPEG_SERVER_PORT=20022 test

User defaults from command line:
    IDEDerivedDataPathOverride = /opt/tools/mcloud-ios/tmp/DerivedData/d6afc6b3a65584ca0813eb8957c6479b9b6ebb11

Build settings from command line:
    MJPEG_SERVER_PORT = 20022
    USE_PORT = 20021

2021-01-04 20:35:24.505 xcodebuild[81924:168197098]  DTDeviceKit: deviceType from 63525e40ca01eef5362dc0c1bf4e6b927401b069 was NULL
2021-01-04 20:35:24.545 xcodebuild[81924:168197110]  DTDeviceKit: deviceType from b09fa26acc4c3f777e9b8b49e3348b7243f862b5 was NULL
2021-01-04 20:35:24.552 xcodebuild[81924:168197097]  DTDeviceKit: deviceType from d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 was NULL
2021-01-04 20:35:24.613 xcodebuild[81924:168197275]  DTDeviceKit: deviceType from 63525e40ca01eef5362dc0c1bf4e6b927401b069 was NULL
2021-01-04 20:35:24.614 xcodebuild[81924:168197275]  DTDeviceKit: deviceType from 63525e40ca01eef5362dc0c1bf4e6b927401b069 was NULL
2021-01-04 20:35:24.715 xcodebuild[81924:168197278]  DTDeviceKit: deviceType from b09fa26acc4c3f777e9b8b49e3348b7243f862b5 was NULL
2021-01-04 20:35:24.715 xcodebuild[81924:168197278]  DTDeviceKit: deviceType from b09fa26acc4c3f777e9b8b49e3348b7243f862b5 was NULL
2021-01-04 20:35:24.725 xcodebuild[81924:168197098]  DTDeviceKit: deviceType from d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 was NULL
2021-01-04 20:35:24.725 xcodebuild[81924:168197098]  DTDeviceKit: deviceType from d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 was NULL
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Using build description from disk

2021-01-04 20:35:27.044 xcodebuild[81924:168197275]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/opt/tools/mcloud-ios/tmp/DerivedData/d6afc6b3a65584ca0813eb8957c6479b9b6ebb11/Logs/Test/Test-WebDriverAgentRunner-2021.01.04_20-35-25-+0300.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-DEAC3A0F-A61B-4BDA-B448-4258D7B099B3/WebDriverAgentRunner-4B69266B-FD17-4E07-AA39-900D6B7F6B9A/Session-WebDriverAgentRunner-2021-01-04_203527-IevXAI.log
2021-01-04 20:35:27.045 xcodebuild[81924:168197015] [MT] IDETestOperationsObserverDebug: (B082686D-A3F7-40E5-AD6F-D1FC71BA5F46) Beginning test session WebDriverAgentRunner-B082686D-A3F7-40E5-AD6F-D1FC71BA5F46 at 2021-01-04 20:35:27.044 with Xcode 12B45b on target 📱<DVTiOSDevice (0x7fe93db29240), STAG_iPhone_8_Plus, iPhone, 14.2 (18B92), d6afc6b3a65584ca0813eb8957c6479b9b6ebb11> {
		deviceSerialNumber:         C38V961BJCM2
		identifier:                 d6afc6b3a65584ca0813eb8957c6479b9b6ebb11
		deviceClass:                iPhone
		deviceName:                 STAG_iPhone_8_Plus
		deviceIdentifier:           d6afc6b3a65584ca0813eb8957c6479b9b6ebb11
		productVersion:             14.2
		buildVersion:               18B92
		deviceSoftwareVersion:      14.2 (18B92)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        57237696512
		deviceAvailableCapacity:    51604987904
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsPaired:             YES
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fe93d234190 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		hasWritableSystem:         NO
		isSupportedOS:             YES
		bootArgs:                  (null)
		nextBootArgs:              (null)
		connected:                 YES
		isWirelessEnabled:         NO
		connectionType:            direct
		hostname:                  (null)
		bonjourServiceName:        b0:19:c6:f3:8c:d3@fe80::b219:c6ff:fef3:8cd3._apple-mobdev2._tcp.local.
		activeProxiedDevice:       (null)
		} (14.2 (18B92))
2021-01-04 20:35:27.157 xcodebuild[81924:168197015] [MT] IDETestOperationsObserverDebug: (B082686D-A3F7-40E5-AD6F-D1FC71BA5F46) Finished requesting crash reports. Continuing with testing.
2021-01-04 20:35:30.778134+0300 WebDriverAgentRunner-Runner[11376:7830720] Running tests...
Test Suite 'All tests' started at 2021-01-04 20:35:31.285
Test Suite 'WebDriverAgentRunner.xctest' started at 2021-01-04 20:35:31.286
Test Suite 'UITestingUITests' started at 2021-01-04 20:35:31.286
    t =      nans Suite Set Up
2021-01-04 20:35:31.305402+0300 WebDriverAgentRunner-Runner[11376:7830720] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x281e46600> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-01-04 20:35:31.314862+0300 WebDriverAgentRunner-Runner[11376:7830720] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x281e46600> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-01-04 20:35:31.315682+0300 WebDriverAgentRunner-Runner[11376:7830720] [User Defaults] Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x281e46600> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-01-04 20:35:31.317885+0300 WebDriverAgentRunner-Runner[11376:7830720] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x281e46600> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2021-01-04 20:35:31.319
    t =     0.00s Set Up
2021-01-04 20:35:31.326319+0300 WebDriverAgentRunner-Runner[11376:7830720] Built at Dec 23 2020 21:06:35
2021-01-04 20:35:31.342088+0300 WebDriverAgentRunner-Runner[11376:7830720] ServerURLHere->http://192.168.89.20:20021<-ServerURLHere
2021-01-04 20:35:31.342467+0300 WebDriverAgentRunner-Runner[11376:7830845] Using singleton test manager
2021-01-04 20:35:31.772171+0300 WebDriverAgentRunner-Runner[11376:7830720] [TraitCollection] Class CKBrowserSwitcherViewController overrides the -traitCollection getter, which is not supported. If you're trying to override traits, you must use the appropriate API.
2021-01-04 20:35:32.549744+0300 WebDriverAgentRunner-Runner[11376:7830720] Getting the most recent active application (out of 1 total items)
    t =     1.25s Find the Application 'com.apple.springboard'
    t =     1.26s     Requesting snapshot of accessibility hierarchy for app with pid 59
2021-01-04 20:38:13.200968+0300 WebDriverAgentRunner-Runner[11376:7830873] Got screenshots broadcast client connection at 192.168.89.189:64803
2021-01-04 20:38:13.201831+0300 WebDriverAgentRunner-Runner[11376:7830873] Starting screenshots broadcast for the client at 192.168.89.189:64803
2021-01-04 20:42:03.506984+0300 WebDriverAgentRunner-Runner[11376:7831252] Disconnected a client from screenshots broadcast

```

**Comment by vdelendik** [comment] 2022-01-21 00:18
@dhreben, closing as can't reproduce. let's retest and provide more detailed steps howto repro...

**Closed by vdelendik** 2022-01-21 00:18 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2022-01-21 12:44
Closed
Cant reproduce
