### ISSUE TITLE
Mcloud-ios services are not up and running after restart mcloud

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#191] opened 2023-01-18 07:15 UTC
**Steps:**

1. cd ../mcloud/
2. ./zebrunner.sh restart
3. Open mcloud-ios
4. ./zebrunnre.sh status --> all devices and simulators have **unhealtry** status
5. Open STF --> devices and simulators are not available.

**Actual result:** Mcloud-ios services are not up and running after restart mcloud on STF

**Workaround:**
../mcloud-ios$ ./zebrunner.sh restart

**Logs:** 

```
idmclouds-Mac-mini:mcloud-ios idmcloud$ tail -f ./logs/agents.log
iPhone_8 (b09fa...............e3348b7243f862b5): Start services for attached device.
{"level":"warning","msg":"there is already a developer image mounted, reboot the device if you want to remove it. aborting.","time":"2023-01-18T00:58:40+03:00"}
{"basedir":"./devimages","level":"info","msg":"success mounting image","time":"2023-01-18T00:58:40+03:00","udid":"b0............7243f862b5"}
iPhone_8 (b09.............8b7243f862b5)
iPhone_8 (b0.............43f862b5)
iPhone_8 (b0...........f862b5) is healthy.
Recover services for Apple_TV (DBF722DB-C6BB-4F72-9828-438DE90795B7)
Recover services for iPad_9 (00008030-001445C20260C02E)
Recover services for iPhone_8 (b09f............43f862b5)
Recover services for Apple_TV (DBF722DB-C6BB-4F72-9828-438DE90795B7)

```

**Logs 2:** 

```
idmclouds-Mac-mini:mcloud-ios idmcloud$ tail -n 100 -f ./logs/iPhone_8.log
Starting WDA: iPhone_8, udid: b0.............b49e3348b7243f862b5, WDA_PORT: 20001, MJPEG_PORT: 20002
[18/01/2023 09:44:51] Starting WebDriverAgent application on port 20001
{"bundleid":"com.facebook.WebDriverAgentRunner.xctrunner","level":"info","msg":"Running wda","testbundleid":"com.facebook.WebDriverAgentRunner.xctrunner","time":"2023-01-18T09:44:52+03:00","xctestconfig":"WebDriverAgentRunner.xctest"}
WDA not started yet on iPhone_8. waiting 0 sec...
WDA not started yet on iPhone_8. waiting 1 sec...
{"bundleID":"com.facebook.WebDriverAgentRunner.xctrunner","channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Launching process","time":"2023-01-18T09:44:54+03:00"}
{"channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Process started successfully","pid":30754,"time":"2023-01-18T09:44:54+03:00"}
{"fields.msg":"2023-01-18 09:44:54.544083+0300 WebDriverAgentRunner-Runner[30754:1807626] Running tests...\n","fields.time":11426719051227,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:54+03:00"}
WDA not started yet on iPhone_8. waiting 2 sec...
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginExecutingTestPlan","time":"2023-01-18T09:44:55+03:00"}
WDA not started yet on iPhone_8. waiting 3 sec...
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginInitializingForUITesting","time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"Test Suite 'All tests' started at 2023-01-18 09:44:56.468\n","fields.time":11426765256060,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"XCTestOutputBarrierTest Suite 'WebDriverAgentRunner.xctest' started at 2023-01-18 09:44:56.470\nXCTestOutputBarrierTest Suite 'UITestingUITests' started at 2023-01-18 09:44:56.470\nXCTestOutputBarrier    t =      nans Suite Set Up\n","fields.time":11426765284912,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.509172+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    KeyboardAutocorrection\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766212837,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.511543+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_changedAt\"\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766269794,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.511977+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_buildAtChange\"\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766279437,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.512348+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_previousValue\"\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766287553,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.512734+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_analyzedAt\"\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766296267,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.530336+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    KeyboardPrediction\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766722248,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.530840+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    KeyboardShowPredictionBar\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766742491,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.531879+0300 WebDriverAgentRunner-Runner[30754:1807626] [User Defaults] Couldn't write values for keys (\n    DidShowGestureKeyboardIntroduction\n) in CFPrefsPlistSource\u003c0x281d4ae00\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","fields.time":11426766760104,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCaseDidStartForTestClass:method:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"Test Case '-[UITestingUITests testRunner]' started.\n","fields.time":11426766938106,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"XCTestOutputBarrier","fields.time":11426766961698,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"    t =     0.00s Start Test at 2023-01-18 09:44:56.540\n","fields.time":11426766976374,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"    t =     0.00s Set Up\n","fields.time":11426767004137,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.543217+0300 WebDriverAgentRunner-Runner[30754:1807626] Built at Jan 12 2023 16:18:28\n","fields.time":11426767028173,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.606278+0300 WebDriverAgentRunner-Runner[30754:1807626] ServerURLHere-\u003ehttp://192.168.88.208:20001\u003c-ServerURLHere\n","fields.time":11426768543942,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
{"fields.msg":"2023-01-18 09:44:56.606631+0300 WebDriverAgentRunner-Runner[30754:1807636] Using singleton test manager\n","fields.time":11426768552984,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:44:56+03:00"}
WDA started successfully on iPhone_8 within 4 seconds.
{"fields.msg":"2023-01-18 09:45:10.314787+0300 WebDriverAgentRunner-Runner[30754:1807636] Got screenshots broadcast client connection at 127.0.0.1:56850\n","fields.time":11427097553398,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:45:10+03:00"}
{"fields.msg":"2023-01-18 09:53:35.382266+0300 WebDriverAgentRunner-Runner[30754:1807640] Disconnected a client from screenshots broadcast\n","fields.time":11439218462002,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":30754,"time":"2023-01-18T09:53:35+03:00"}
43f862b5',
  provider: 'mcloud-ios',
  publicIp: 'demo.zebrunner.farm',
  endpoints: {
    sub: [ 'tcp://demo.zebrunner.farm:7250' ],
    push: [ 'tcp://demo.zebrunner.farm:7270' ],
    appDealer: [ 'tcp://demo.zebrunner.farm:7160' ],
    devDealer: [ 'tcp://demo.zebrunner.farm:7260' ]
  },
  groupTimeout: 3600000,
  storageUrl: 'https://demo.zebrunner.farm:443/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 30,
  screenPingInterval: 30000,
  screenPort: 7701,
  screenWsUrlPattern: 'wss://demo.zebrunner.farm:443/d/192.168.89.189/b09f.............8b7243f862b5/7701/',
  connectUrlPattern: '${publicIp}:${publicPort}',
  connectPort: 20002,
  wdaHost: 'localhost',
  wdaPort: 20001,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: false,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  deviceName: 'iPhone_8',
  deviceType: 'Phone',
  host: '192.168.89.189'
}
2023-01-18T06:45:10.331Z INF/device:support:sub 42187 [b09fa............e3348b7243f862b5] Receiving input from "tcp://demo.zebrunner.farm:7250"
2023-01-18T06:45:10.334Z INF/device:support:sub 42187 [b09f...........48b7243f862b5] Subscribing to permanent channel "*ALL"
2023-01-18T06:45:10.339Z INF/device:plugins:solo 42187 [b..........49e3348b7243f862b5] Subscribing to permanent channel "dzTlyg6o9YlxdBizOqIGbhlToWI="
2023-01-18T06:45:10.343Z INF/wdaClient 42187 [b0...........e3348b7243f862b5] WdaClient.js initializing...
connecting to WdaMjpeg
2023-01-18T06:45:10.355Z INF/device:info 42187 [b............9e3348b7243f862b5] device.name: iPhone_8
Connected to WdaMjpeg localhost:20002
2023-01-18T06:53:35.217Z WRN/db 42187 [b0............49e3348b7243f862b5] Connection closed
2023-01-18T06:53:35.220Z INF/db 42187 [b0............e3348b7243f862b5] Connecting to demo.zebrunner.farm:28015
2023-01-18T06:53:35.340Z INF/db 42187 [b............8b49e3348b7243f862b5] Unable to connect to demo.zebrunner.farm:28015
2023-01-18T06:53:35.344Z FTL/db 42187 [b0.............b49e3348b7243f862b5] No hosts left to try
2023-01-18T06:53:35.346Z FTL/util:lifecycle 42187 [b.............e3348b7243f862b5] Shutting down due to fatal error with optional error :  undefined
```

**Comment by vdelendik** [comment] 2023-03-06 23:07
closing as dupe of #196

**Closed by vdelendik** 2023-03-06 23:07 UTC
Labels: bug, duplicate
