### ISSUE TITLE
TypeError: Cannot read property 'close' of null after ./zebrunner.sh start-stf [udid]

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#25] opened 2021-01-04 18:14 UTC
**Test scenario:**

Steps:

1../zebrunner.sh down
2../zebrunner.sh start-stf [udid]
3.tail -n1000 -f ./logs/stf_iPhone_8_plus.log
**Actual resutl:** TypeError: Cannot read property 'close' of null after ./zebrunner.sh start-stf [udid]

```
2021-01-04T17:20:51.400Z INF/device:support:sub 52235 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Receiving input from "tcp://stage.solvd.com:7250"
2021-01-04T17:20:51.402Z INF/device:support:sub 52235 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Subscribing to permanent channel "*ALL"
2021-01-04T17:20:51.403Z INF/device:plugins:solo 52235 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Subscribing to permanent channel "L31XyM0DStL3GxTJ+UhrWOum7+M="
2021-01-04T17:35:53.947Z INF/db 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Connecting to stage.solvd.com:28015
2021-01-04T17:35:53.985Z INF/device:support:push 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Ios device sending output to "tcp://stage.solvd.com:7270"
2021-01-04T17:35:53.988Z INF/device 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Preparing device options:  { serial: 'd6afc6b3a65584ca0813eb8957c6479b9b6ebb11',
  provider: '192.168.89.189',
  publicIp: 'stage.solvd.com',
  endpoints: 
   { sub: [ 'tcp://stage.solvd.com:7250' ],
     push: [ 'tcp://stage.solvd.com:7270' ],
     appDealer: [ 'tcp://stage.solvd.com:7160' ],
     devDealer: [ 'tcp://stage.solvd.com:7260' ] },
  groupTimeout: 3600000,
  storageUrl: 'http://stage.solvd.com/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 40,
  screenPingInterval: 30000,
  screenPort: 7721,
  screenWsUrlPattern: 'ws://stage.solvd.com/d/192.168.89.189/d6afc6b3a65584ca0813eb8957c6479b9b6ebb11/7721/',
  connectUrlPattern: '${publicIp}:${publicPort}',
  connectPort: 20022,
  wdaHost: '192.168.89.20',
  wdaPort: 20021,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: false,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  appiumHost: '192.168.89.189',
  appiumPort: 4843,
  proxyAppiumPort: 7730,
  deviceName: 'iPhone_8_Plus',
  deviceType: 'phone' }
2021-01-04T17:35:54.353Z INF/device:support:sub 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Receiving input from "tcp://stage.solvd.com:7250"
2021-01-04T17:35:54.357Z INF/device:support:sub 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Subscribing to permanent channel "*ALL"
2021-01-04T17:35:54.359Z INF/device:plugins:solo 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Subscribing to permanent channel "L31XyM0DStL3GxTJ+UhrWOum7+M="
2021-01-04T17:38:11.832Z IMP/device:plugins:group 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Now owned by "dhreben@solvd.com"
2021-01-04T17:38:11.832Z INF/device:plugins:group 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Subscribing to group channel "ReBZM+3AScWGobBJK6vWuQ=="
2021-01-04T17:38:13.041Z IMP/device:plugins:group 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] No longer owned by "dhreben@solvd.com"
2021-01-04T17:38:13.042Z INF/device:plugins:group 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Unsubscribing from group channel "ReBZM+3AScWGobBJK6vWuQ=="
2021-01-04T17:38:13.044Z ERR/remote debug 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] TypeError: Cannot read property 'close' of null
    at Promise (/opt/tools/stf/lib/util/AppiumProxyServer.js:65:33)
    at AppiumProxyServer.disconnect (/opt/tools/stf/lib/util/AppiumProxyServer.js:63:16)
    at disconnectProxyServer (/opt/tools/stf/lib/units/ios-device/plugins/remotedebug.js:21:25)
    at EventEmitter.group.on (/opt/tools/stf/lib/units/ios-device/plugins/remotedebug.js:47:13)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at plugin.get.then.group (/opt/tools/stf/lib/units/ios-device/plugins/group.js:89:17)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at EventEmitter.plugin.leave (/opt/tools/stf/lib/units/ios-device/plugins/group.js:72:10)
    at Promise.method (/opt/tools/stf/lib/units/ios-device/plugins/group.js:146:27)
From previous event:
    at Router.router.on.on.on (/opt/tools/stf/lib/units/ios-device/plugins/group.js:147:13)
    at Router.emit (/opt/tools/stf/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/opt/tools/stf/lib/wire/router.js:35:12)
    at emitTwo (events.js:131:20)
    at exports.Socket.emit (events.js:214:7)
    at exports.Socket.Socket._flushRead (/opt/tools/stf/node_modules/zmq/lib/index.js:638:15)
    at exports.Socket.Socket._flushReads (/opt/tools/stf/node_modules/zmq/lib/index.js:676:23)
    at Object._zmq.onReadReady (/opt/tools/stf/node_modules/zmq/lib/index.js:297:10)
2021-01-04T17:38:13.048Z IMP/device:plugins:screen:stream 83561 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] ws on close event
```

**Comment by vdelendik** [comment] 2022-01-20 22:26
@dhreben, closing as not a bug. You killed everything including appium and wda and start only stf!
to operate with devices we mush have both wda and stf started.

**Closed by vdelendik** 2022-01-20 22:26 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2022-01-21 13:12
Closed,not a bug
